@server = http://localhost:4004
@auth = Authorization: Basic alice:


### SalesOrders
# @name AssetVault_GET
GET {{server}}/odata/v4/asset-vault/AssetVault
{{auth}}

### SalesOrders
# @name AssetVault_POST
POST {{server}}/odata/v4/asset-vault/DistributionDcp
{{auth}}
Content-Type: application/json

{
    "AnnotationText": "LiloAndStitch2025_FTR_EN-OV_CCAP_-ATMOS-HI-VI_2D-DVIS_SMPTE_MERGED_20250509",
    "AnyAtmos": 1,
    "AnyCCAP": 1,
    "AnyHI": 1,
    "AnyOCAP": 0,
    "AnySLV": 0,
    "AnyVI": 1,
    "AspectRatio": "Scope",
    "AssetMapFileSize": "320654760000",
    "AssetMapID": "bcd52685-b2f4-463e-aee4-e571e6c31415",
    "AssetMapIDDescription": "Lilo & Stitch (2025) US Dolby Vision Release",
    "AudioFormats": "5.1,7.1,MOS",
    "CreatedinSAP": false,
    "DCP": null,
    "DcpFormats": "SMPTEA,SMPTEB20,SMPTEB21",
    "EDeliveryApacTitleId": null,
    "EDeliveryNoramTitleId": "3XjKYRRQMMGLQDR5u",
    "ExternalReference": null,
    "KencastID": "bcd52685-b2f4-463e-aee4-e571e6c31415",
    "KrakenTitleID": "53712",
    "MaxCPLDuration": "01:47:31:23",
    "PictureFormats": "5.1,7.1,MOS",
    "ProductionProcess": null,
    "ProjectID": "1468924",
    "ProjectType": "2",
    "PublishDaysBeforePlaydate": "7",
    "Resolution": "2K,4K",
    "SatelliteDistributionEndDate": "2025-06-27T00:00:00-07:00",
    "SatelliteDistributionStartDate": "2025-05-19T00:00:00-07:00",
    "StartOfCrawl": "01:40:14:06",
    "StartOfCredit": "01:36:19:13",
    "Title": null,
    "VersionDescription": "US Dolby Vision Release",
    "VolumeName": "LiloAndStitch2025_FTR_EN-OV_CCAP_-ATMOS-HI-VI_2D-DVIS_SMPTE_MERGED_20250509",
    "_Items": [
        {
            "AspectRatio": "Scope",
            "AssetMapUUID": "32b81d96-c871-47f1-8ad2-4288b1da0b54",
            "AtmosFlag": 1,
            "CPLS3location": null,
            "ClosedCaptionsFlag": 1,
            "ContentKind": "Unknown",
            "DCDMFlag": "False",
            "DKDMS3location": null,
            "DcpFormatType": "SMPTEB21",
            "DcpProjectID": "1455169",
            "DcpResolution": "2K",
            "DistributionSize": "308579835417",
            "Download": null,
            "Email": null,
            "KDMFlag": null,
            "LinkedCPLUUID": "917969ca-60b6-42de-ae9c-02c7be4d06af",
            "LinkedCTT": "LiloStitch2025_FTR-4-2D-DVis_S_EN-EN-CCAP_US-PG_IAB-HI-VI_2K_DLA_20250423_WDS_SMPTE_OV",
            "LinkedDCP": "32b81d96-c871-47f1-8ad2-4288b1da0b54",
            "PictureFormat": "2D",
            "ProjectTypeID": "1",
            "RunTime": "01:47:31:23",
            "SignLanguageVideoFlag": 0,
            "SoundFormat": "MOS",
            "StartOfCrawl": "01:40:14:06",
            "StartOfCredits": "01:36:19:13",
            "VersionDescription": "EDR"
        },
        {
            "AspectRatio": "Scope",
            "AssetMapUUID": "0d98644a-e460-4c94-a18e-13ca655e515f",
            "AtmosFlag": 1,
            "CPLS3location": null,
            "ClosedCaptionsFlag": 1,
            "ContentKind": "Unknown",
            "DCDMFlag": "False",
            "DKDMS3location": null,
            "DcpFormatType": "SMPTEB21",
            "DcpProjectID": "1415257",
            "DcpResolution": "2K",
            "DistributionSize": "2461061631",
            "Download": null,
            "Email": null,
            "KDMFlag": null,
            "LinkedCPLUUID": "72126481-0b87-43f8-9601-c21f13c47c6d",
            "LinkedCTT": "FreakierFriday_TLR-2-2D-DVis_S_EN-EN-CCAP_US-GB_IAB-HI-51_2K_DI_20250305_DLX_SMPTE_OV",
            "LinkedDCP": "0d98644a-e460-4c94-a18e-13ca655e515f",
            "PictureFormat": "2D",
            "ProjectTypeID": "1",
            "RunTime": "00:01:50:04",
            "SignLanguageVideoFlag": 0,
            "SoundFormat": "5.1",
            "StartOfCrawl": null,
            "StartOfCredits": null,
            "VersionDescription": "EDR TLR-2"
        },
        {
            "AspectRatio": "Scope",
            "AssetMapUUID": "0bf10655-d2f2-40d4-832c-e9f481566c56",
            "AtmosFlag": 1,
            "CPLS3location": null,
            "ClosedCaptionsFlag": 1,
            "ContentKind": "Unknown",
            "DCDMFlag": "False",
            "DKDMS3location": null,
            "DcpFormatType": "SMPTEB21",
            "DcpProjectID": "1441967",
            "DcpResolution": "4K",
            "DistributionSize": "4284706886",
            "Download": null,
            "Email": null,
            "KDMFlag": null,
            "LinkedCPLUUID": "5a0f5ae4-5721-4ecc-90cf-63a11d618b5c",
            "LinkedCTT": "Fantastic42025_TLR-2-2D-DVis_S_EN-EN-CCAP_US-GB_IAB-HI-51_4K_DI_20250413_DLX_SMPTE_OV",
            "LinkedDCP": "0bf10655-d2f2-40d4-832c-e9f481566c56",
            "PictureFormat": "2D",
            "ProjectTypeID": "1",
            "RunTime": "00:02:30:02",
            "SignLanguageVideoFlag": 0,
            "SoundFormat": "5.1",
            "StartOfCrawl": null,
            "StartOfCredits": null,
            "VersionDescription": "TLR-2"
        },
        {
            "AspectRatio": "Scope",
            "AssetMapUUID": "b358f453-5ca5-4088-96ba-91b69c9a8c6e",
            "AtmosFlag": 1,
            "CPLS3location": null,
            "ClosedCaptionsFlag": 1,
            "ContentKind": "Unknown",
            "DCDMFlag": "False",
            "DKDMS3location": null,
            "DcpFormatType": "SMPTEB21",
            "DcpProjectID": "1454259",
            "DcpResolution": "4K",
            "DistributionSize": "1475884032",
            "Download": null,
            "Email": null,
            "KDMFlag": null,
            "LinkedCPLUUID": "3573ecd8-b3b5-4501-a71b-023de9f0a281",
            "LinkedCTT": "Zootopia2_TLR-1-2D-DVis_S_EN-EN-CCAP_US-GB_IAB-HI-51_4K_DI_20250502_DLX_SMPTE_OV",
            "LinkedDCP": "b358f453-5ca5-4088-96ba-91b69c9a8c6e",
            "PictureFormat": "2D",
            "ProjectTypeID": "1",
            "RunTime": "00:01:28:19",
            "SignLanguageVideoFlag": 0,
            "SoundFormat": "5.1",
            "StartOfCrawl": null,
            "StartOfCredits": null,
            "VersionDescription": "TLR-1"
        },
        {
            "AspectRatio": "Scope",
            "AssetMapUUID": "1904f847-12b6-4eb5-9636-2937aa20dac6",
            "AtmosFlag": 1,
            "CPLS3location": null,
            "ClosedCaptionsFlag": 1,
            "ContentKind": "Unknown",
            "DCDMFlag": "False",
            "DKDMS3location": null,
            "DcpFormatType": "SMPTEB21",
            "DcpProjectID": "1459833",
            "DcpResolution": "2K",
            "DistributionSize": "3302736329",
            "Download": null,
            "Email": null,
            "KDMFlag": null,
            "LinkedCPLUUID": "e8cf4722-790c-47b4-9caf-4a049334adc6",
            "LinkedCTT": "Elio_TLR-4-2D-DVis_S_EN-EN-CCAP_US-GB_IAB-HI-51_2K_DI_20250506_DLX_SMPTE_OV",
            "LinkedDCP": "1904f847-12b6-4eb5-9636-2937aa20dac6",
            "PictureFormat": "2D",
            "ProjectTypeID": "1",
            "RunTime": "00:02:03:09",
            "SignLanguageVideoFlag": 0,
            "SoundFormat": "5.1",
            "StartOfCrawl": null,
            "StartOfCredits": null,
            "VersionDescription": "TLR-4"
        },
        {
            "AspectRatio": "Scope",
            "AssetMapUUID": "1f8fa3b3-85e4-4041-98b6-0c45fb358209",
            "AtmosFlag": 0,
            "CPLS3location": null,
            "ClosedCaptionsFlag": 0,
            "ContentKind": "Unknown",
            "DCDMFlag": "False",
            "DKDMS3location": null,
            "DcpFormatType": "SMPTEA",
            "DcpProjectID": "723562",
            "DcpResolution": "2K",
            "DistributionSize": "518062391",
            "Download": null,
            "Email": null,
            "KDMFlag": null,
            "LinkedCPLUUID": "883d9b97-ec9a-48e6-a5ed-0d69c5bd6f0e",
            "LinkedCTT": "DisneyDigital_DLX-71_2D-FramingChart_C-239_EN-XX_INT_71-HI-VI_2K_DI_20211215_DLX_SMPTE_OV",
            "LinkedDCP": "1f8fa3b3-85e4-4041-98b6-0c45fb358209",
            "PictureFormat": "2D",
            "ProjectTypeID": "1",
            "RunTime": "00:01:00:00",
            "SignLanguageVideoFlag": 0,
            "SoundFormat": "7.1",
            "StartOfCrawl": null,
            "StartOfCredits": null,
            "VersionDescription": "DLX Generic Framing Chart SMPTE"
        },
        {
            "AspectRatio": "Scope",
            "AssetMapUUID": "5d69d689-2fdf-4ade-aa27-f5edd6a57054",
            "AtmosFlag": 0,
            "CPLS3location": null,
            "ClosedCaptionsFlag": 0,
            "ContentKind": "Unknown",
            "DCDMFlag": "False",
            "DKDMS3location": null,
            "DcpFormatType": "SMPTEB20",
            "DcpProjectID": "616446",
            "DcpResolution": "2K",
            "DistributionSize": "32479506",
            "Download": null,
            "Email": null,
            "KDMFlag": null,
            "LinkedCPLUUID": "ee85b9f0-6158-49dd-a1c2-89adaa5e8a4f",
            "LinkedCTT": "PG_RTG-2D_S-178_EN-XX_US-PG_MOS_2K_20191004_CVN_SMPTE_OV",
            "LinkedDCP": "5d69d689-2fdf-4ade-aa27-f5edd6a57054",
            "PictureFormat": "2D",
            "ProjectTypeID": "1",
            "RunTime": "00:00:05:02",
            "SignLanguageVideoFlag": 0,
            "SoundFormat": "5.1",
            "StartOfCrawl": null,
            "StartOfCredits": null,
            "VersionDescription": null
        }
    ]
}